---
- hosts: all
  gather_facts: true
  tasks:
    - name: Create variables
      set_fact:
        db_file_name: "15dalo_{{ ansible_date_time.date | replace('-','') }}.sql"
    - name: Confirm hostname
      debug:
        msg: Logged into the server.
    - name: Dump database
      shell: |
        mysqldump -u root -pPr0fess10n@L 15dalo > /home/sysadmin/"{{ db_file_name }}"
      no_log: true
    - name: Wait until the database backup completed on server
      wait_for:
        path: "{{ db_file_name }}"
        state: present
        msg: "Timeout to find file {{ db_file_name }}"
