---
- hosts: all
  gather_facts: true
  vars_files:
    - database_vault.yaml
  tasks:
    - name: Create variables
      set_fact:
        db_file_name: "15dalo.sql"
    
    - name: Confirm hostname
      debug:
        msg: Logged into the server.

    - name: Backup Database named 15dalo
      shell: |
        mysqldump -u root -pPr0fess10n@L 15dalo --quick --lock-tables=false > /home/sysadmin/15dalo.sql --no-tablespaces
      no_log: true
    - name: Wait until the database backup completed on server
      wait_for:
        path: "{{ db_file_name }}"
        state: present
        msg: "Timeout to find file {{ db_file_name }}"
