---
- hosts: all
  gather_facts: true
  vars_files:
    - database_vault.yaml
  tasks:
    - name: Create variables
      set_fact:
        db_file_name: "15dalo.sql"
    - name: Confirm hostname
      debug:
        msg: Logged into the server.
    - name: Backup Database named 15dalo
      community.mysql.mysql_db:
        state: dump
        name: 15dalo
        target: /home/sysadmin/15dalo.sql    
    - name: Wait until the database backup completed on server
      wait_for:
        path: "{{ db_file_name }}"
        state: present
        msg: "Timeout to find file {{ db_file_name }}"
